<?php

function get_authrealeaseString(){
  $authrelease = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Pdf Strings</title>
<link rel="stylesheet" href="preapp_complete.css" type="text/css" media="screen" />

</head>

<body>

<div id="content-pdf">
<div id="logo"><img src="logo.png"/></div>
<div id="title">
<h1>Physician Application Step 1</h1>
<h2>Submitted July, 7 2013 7:15 PM MST</h2>
<h2>For Megan Johnson</h2>
</div>
<div id="auth-txt">
<p>I, Megan Johnson, hereby authorize all medical schools, university transcript
offices, medical institutions or organizations, personal references, physicians,
attorneys, employers, medical malpractice insurance carriers or organizations,
business and professional associates, all government agencies and
instrumentalities (local, state, federal, or foreign), all health care providers, the
American Medical Association and/or the American Osteopathic Association,
the National Practitioner Data Bank and the Federation of State Medical Boards
to release to state licensing boards and to VISTA Staffing Solutions and VISTA
HealthCare Partners any information, opinions, files, transcripts, or records required
by that particular board or by VISTA Staffing Solutions and VISTA HealthCare
Partners for its evaluation of my qualifications for credentialing and for medical
licensing purposes. I hereby give my permission for representatives of VISTA
Staffing Solutions and VISTA HealthCare Partners to discuss my application
information with clients and licensing boards, and hereby waive any privilege of
confidentiality of such information for the purpose indicated herein.</p>

<p>I consent to the release of all information necessary, including that which otherwise
is privileged or confidential, to evaluate my qualifications, character, professional
ethics and competence to practice medicine in my specialty. This includes
information relative to any treatment for or the existence of a condition that could
impair my ability to practice medicine with reasonable skill and safety, including
infectious diseases, psychiatric and mental health conditions, and alcohol and
drug abuse.</p>

<p>I, the undersigned, release all organizations and individuals from all liability for
any damages that may result from providing this information. I agree that neither
VISTA Staffing Solutions nor VISTA HealthCare Partners is under any obligation
to disclose to me any of the information collected for credentialing, referencing,
and licensing purposes except pursuant to subpoena. This consent for release of
information may be revoked by me anytime in writing. However, any party, program
or person making disclosure prior to receipt of such revocation is deemed as having
acted in good faith based on this document. If not previously revoked, this Release
and Authorization will terminate two years from the date on this document.</p>

<p>The original or a copy hereof shall operate as full proof of authority and release.</p>

</div>
<p><input type="checkbox" checked class="checkbox" />By checking this box you agree that all your information is correct….
NEED FROM LEGAL DEPARTMENT.</p>




</div>
</body>
</html>';

  return $authrelease;
}
